POLL_HTMLTILE=Poll
POLL_BUTTON_SAVE=Save
POLL_BUTTON_DELETE=Delete
POLL_BUTTON_START=Start voting
POLL_BUTTON_STOP=Stop voting
POLL_BUTTON_ABORT=Abort
POLL_BUTTON_CLOSE=Close
POLL_QUESTION=Question:
POLL_STATUS=Status:
POLL_STATUS_NOT_EXIST=Not Exists
POLL_STATUS_NEW=New
POLL_STATUS_RUNNING=Voting
POLL_STATUS_STOPPED=Stopped
POLL_STATUS_ABORTED=Aborted
POLL_SITE=Site:
POLL_TYPE=Type:
POLL_TYPE_SINGLE_ANSWER=Single Answer
POLL_TYPE_MULTIPLE_CHOICE=Multiple Choice
POLL_VIEW=View:
POLL_VIEW_HORIZONTAL_BAR=Horizontal Bar
POLL_VIEW_VERTICAL_BAR=Vertical Bar
POLL_VIEW_PIE=Pie
POLL_VOTE=Limits to voter:
POLL_ALLOW_SAME_IP=Allow users from same IP
POLL_SAME_IP_INTERVAL=but can vote after
POLL_HINT_SAME_IP_INTERVAL=Empty=No time limit
POLL_MEMBER_ONLY=For members only
POLL_CREATOR=Created by:
POLL_CREATEDATE=Created at:
POLL_OPTIONS=Options:
POLL_BUTTON_ADD_OPTION=Add
POLL_BUTTON_DEL_OPTION=Delete
POLL_OPTION=Title
POLL_OPTION_COUNT=Vote(s)
POLL_CODE=Insert codes below to start
POLL_PREVIEW=Preview
POLL_ALERT_QUESTION_IS_NULL=Please input a question
POLL_ALERT_SITE_IS_NULL=Please choose your site
POLL_ALERT_SAVE=All vote(s) will be cleared before saving, are you sure to continue?
POLL_ALERT_DELETE=Are you sure to delete?
POLL_ALERT_START=Are you sure to start voting?
POLL_ALERT_STOP=Are you sure to stop voting?
POLL_ALERT_ABORT=Are you sure to abort voting?
POLL_ALERT_DELETE_OPTION=Are you sure to delete all these options?
POLL_BUTTON_VOTE=Vote
POLL_BUTTON_VIEW=View