RES_HTMLTITLE=File Upload
RES_TITLE=Title
RES_TYPE=File Type
RES_TYPE_AUTO=Auto
RES_TYPE_IMAGE=Image
RES_TYPE_VIDEO=Video
RES_TYPE_AUDIO=Audio
RES_TYPE_DOCUMENT=Document
RES_TYPE_FLASH=Flash
RES_TYPE_OTHER=Other
RES_SCOPE=Scope
RES_SCOPE_GLOBAL=Global
RES_SCOPE_COMPNAY=My Company
RES_SCOPE_SITE=Site Hosted
RES_SITE=Site Hosted
RES_FILE=File
RES_TAG=Add multiple word tags
RES_IMAGE_SCALE=Scale Image
RES_IMAGE_WIDTH=Width
RES_IMAGE_HEIGHT=Height
RES_IMAGE_SCLAE_HINT=<font color=red>Empty for scaling auto</font>
RES_CREATOR=Creator
RES_CREATEDATE=Create At
RES_BUTTON_SAVE=Save
RES_BUTTON_CLOSE=Close
RES_HINT_TAG=Seperating tags by '-'(minus sign) or '_(underscore) or CR
RES_ALERT_NO_TITLE=Please input title
RES_ALERT_NO_SITE=Please choose a site to store the file
RES_ALERT_NO_FILE=Please choose a file
RES_HINT_UPLOADED=&nbsp;uploaded