CRAWLTASKS_HTMLTILE=网站数据抓取作业列表
CRAWLTASKS_BUTTON_NEW=新建
CRAWLTASKS_VIEWLOG=查看日志
CRAWLTASKS_NAME=名称
CRAWLTASKS_RUNAS=运行帐号
CRAWLTASKS_SITE=站点
CRAWLTASKS_CRONEXP=调度周期
CRAWLTASKS_CREATOR=创建人
CRAWLTASKS_CREATEDATE=创建时间
CRAWLTASKS_STATUS=作业状态
CRAWLTASKS_HINT_STATUS_NEW=新建
CRAWLTASKS_HINT_STATUS_BLOCKED=<font color=red>堵塞</font>
CRAWLTASKS_HINT_STATUS_COMPLETE=完成
CRAWLTASKS_HINT_STATUS_ERROR=<font color=red>调度中发生了错误</font>
CRAWLTASKS_HINT_STATUS_NONE=<font color=red>不存在的任务</font>
CRAWLTASKS_HINT_STATUS_NORMAL=正常调度中
CRAWLTASKS_HINT_STATUS_PAUSED=<font color=red>中断中</font>
CRAWLTASKS_STATUS_NOT_SCHEDULED=未提交作业调度