TAG_HTMLTILE=Tag
TAG_BUTTON_SAVE=Save
TAG_BUTTON_DELETE=Delete
TAG_BUTTON_CLOSE=Close
TAG_TITLE=Title:
TAG_NAME=Variable name:
TAG_WAY=Generated from:
TAG_WAY_HTML=Web Pages
TAG_WAY_CONST=Const Value
TAG_NULL=Nullable
TAG_MATCH=Matched:
TAG_MATCH_LOOP=Looply
TAG_MATCH_PAGE=All Next Page(s)
TAG_DOWNLOAD=File Download options:
TAG_DOWNLOAD_IMAGE=Download Images
TAG_DOWNLOAD_FLASH=Download Flashes
TAG_DOWNLOAD_FILE=Download all files ends with
TAG_START=Start from:
TAG_END=To:
TAG_MULTI_RECORDS=Each record matched ( Available for matching looply or all next pages )
TAG_MULTI_RECORDS_NEW=Save as new record
TAG_MULTI_RECORDS_JOIN=Joined with mark
TAG_MULTI_RECORDS_JOIN_STRING=Mark:
TAG_CLEAR=Replace strings:
TAG_BUTTON_ADD_CLEAR=Add
TAG_BUTTON_DEL_CLEAR=Delete
TAG_CLEAR_EXPRESSION=Regular Expression
TAG_CLEAR_REPLACE_STRING=Replace String
TAG_CONST_STRING=String
TAG_CONST_SYSDATE=Sysdate
TAG_HINT_CONST_SYSDATE=Empty=yyyy-MM-dd
TAG_CONST_RANDOM_NUMBER=Random Number
TAG_CONST_RANDOM_NUMBER_FROM=From:
TAG_CONST_RANDOM_NUMBER_TO=To:
TAG_ALERT_TITLE_IS_NULL=Please input title
TAG_ALERT_TAGNAME_IS_NULL=Please input variable name
TAG_ALERT_WAY_IS_NULL=Please choose the way to generate
TAG_ALERT_TAGSTART_IS_NULL=Please input the string started from
TAG_ALERT_TAGEND_IS_NULL=Please input the string ended with
TAG_ALERT_CONSTWAY_IS_NULL=Please choose the way to generate const value
TAG_ALERT_CONSTVALUE_IS_NULL=Please input the const string value
TAG_ALERT_CONST_SYSDATE_FORMAT_IS_NULL=Please input date format
TAG_ALERT_CONST_RANDOM_IS_NULL=Please input the random number
TAG_ALERT_CONST_RANDOM_IS_NOT_NUMBER=The random is not number
TAG_HINT_SAVED= has been saved successfully.
TAG_HINT_DELETED= has been removed successfully.