PAGE_HTMLTILE=web URL
PAGE_BUTTON_SAVE=Save
PAGE_BUTTON_DELETE=Delete
PAGE_BUTTON_CLOSE=Close
PAGE_URL=Web URL:
PAGE_URL_SAMPLE=Sample: http://www.jwebstar.com/index_%1$s.shtml
PAGE_URL_HINT=Variable: %[argument_index$][flags][width][.precision]conversion£¬Ïê¼û<a href="http://download.oracle.com/javase/6/docs/api/java/util/Formatter.html" target=_blank>Formatter</a>
PAGE_GETWAY=Variables:
PAGE_GETWAY_MANUAL=Added below
PAGE_GETWAY_SQL=SQL
PAGE_SQL=SQL:
PAGE_VARS=A list of Variables:
PAGE_BUTTON_ADD_VAR=Add
PAGE_BUTTON_DEL_VAR=Remove
PAGE_VAR_START=Start from
PAGE_VAR_END=to
PAGE_VAR_INC=increased by
PAGE_VAR_MINLENGTH=Min. length
PAGE_VAR_PAD=Left pad
PAGE_ALERT_URL_IS_NULL=Please input web URL
PAGE_HINT_DELETED= has been removed successfully.
PAGE_HINT_SAVED= has  been saved successfully.
PAGE_ALERT_START_IS_NULL=Please input the value to start
PAGE_ALERT_END_IS_NULL=Please input the value to end