SCROLL_ALERT_NOPAGE = 请输入要跳转到的页面
SCROLL_ALERT_PAGENOTEXIST = 该页不存在
SCROLL_RECORDS = 条
SCROLL_PAGES = 页
SCROLL_FIRSTPAGE = 首页
SCROLL_PREVPAGE = 前页
SCROLL_NEXTPAGE = 后页
SCROLL_LASTPAGE = 尾页
SCROLL_HINT_PAGEINPUT=跳转到
 