TRIGGER_HTMLTILE=New Trigger
TRIGGER_ALERT_NAME_IS_NULL=Name is null
TRIGGER_ALERT_TOPIC_IS_NULL==Topic is null
TRIGGER_ALERT_CODE_IS_NULL=Code is null
TRIGGER_ALERT_DELETE=Are you sure to delete this trigger?
TRIGGER_ALERT_ENABLE=Are you sure to enable this trigger?
TRIGGER_ALERT_DISABLE=Are you sure to disable this trigger?
TRIGGER_BUTTON_SAVE=Save
TRIGGER_BUTTON_DELETE=Delete
TRIGGER_BUTTON_ENABLE=Enable
TRIGGER_BUTTON_DISABLE=Disable
TRIGGER_BUTTON_SELTOPIC=Choose
TRIGGER_BUTTON_CLOSE=Close
TRIGGER_NAME=Trigger Name
TRIGGER_ID=ID#
TRIGGER_STATUS=Status
TRIGGER_HINT_STATUS_NEW=New
TRIGGER_HINT_ENABLE=Enabled
TRIGGER_HINT_DISABLE=<font color=red>Disabled</font>
TRIGGER_TOPIC=Topic Listened
TRIGGER_EVENT=Event
TRIGGER_EVENT_INSERT=Insert
TRIGGER_EVENT_UPDATE=Update
TRIGGER_EVENT_READY=Ready to Publish
TRIGGER_EVENT_PUBLISH=Publish
TRIGGER_EVENT_DELETE=Delete
TRIGGER_EVENT_CANCEL=Cancel
TRIGGER_CREATOR=Created By
TRIGGER_CREATEDATE=Created At
TRIGGER_LASTRUN_SERVER=Server
TRIGGER_LASTRUN_STATE=Exit Code
TRIGGER_LASTRUN_STATUS_NORMAL=Normal
TRIGGER_LASTRUN_STATUS_ERROR=<font color=red>Abnormal</font>
TRIGGER_LASTRUN_DATE=Started At
TRIGGER_LASTRUN_TIME=Time(s)
TRIGGER_LANG=Language
TRIGGER_BUTTON_JS_HELP=View Help