JOBADMIN_HTMLTILE=后台作业管理
JOBADMIN_BUTTON_NEW=新建
JOBADMIN_BUTTON_RESUMEALL=全部启用
JOBADMIN_BUTTON_PAUSEALL=全部挂起
JOBADMIN_NAME=名称
JOBADMIN_RUNAS=运行用户
JOBADMIN_SITE=默认站点
JOBADMIN_CRONEXP=运行时间
JOBADMIN_STATUS=状态
JOBADMIN_STATUS_ENABLED=可用
JOBADMIN_STATUS_DISABLED=禁用
JOBADMIN_CREATOR=创建人
JOBADMIN_CREATEDATE=创建时间
JOBADMIN_LATRUNSERVER=服务器
JOBADMIN_LATRUNDATE=运行时间
JOBADMIN_LASTRUN_STATE=运行状态
JOBADMIN_HINT_STATUS_BLOCKED=<font color=red>堵塞</font>
JOBADMIN_HINT_STATUS_COMPLETE=完成
JOBADMIN_HINT_STATUS_ERROR=<font color=red>调度中发生了错误</font>
JOBADMIN_HINT_STATUS_NONE=<font color=red>不存在的任务</font>
JOBADMIN_HINT_STATUS_NORMAL=正常调度中
JOBADMIN_HINT_STATUS_PAUSED=<font color=red>中断中</font>
JOBADMIN_LASTRUN_STATUS_NORMAL=正常完成
JOBADMIN_LASTRUN_STATUS_ERROR=<font color=red>异常退出</font>