SITE_HTMLTITLE=Config Site
SITE_ALERT_SELECT_UNIT_FIRST=Please choose the company
SITE_ALERT_SITEID_NULL=Please input site ID
SITE_ALERT_SITEID_INVALID=Only letter and number are allowed for site ID
SITE_ALERT_NAME_NULL=Please input site name
SITE_ALERT_PUBLISHDIR_NULL=DocumentRoot must be specified
SITE_ALERT_DELETE=All topics,templates,articles will be removed, are you sure to continue?
SITE_ALERT_NO_VARNAME=Please input var name
SITE_ALERT_NO_SOLRFIELDNAME=Please input field name
SITE_BUTTON_SAVE=Save
SITE_BUTTON_EXPORT=Export
SITE_BUTTON_DUMP=Dump
SITE_BUTTON_FREEZE=Disable
SITE_BUTTON_DEFREEZE=Enable
SITE_BUTTON_DELETE=Delete
SITE_BUTTON_ARCHIVE=Archive
SITE_BUTTON_CLOSE=Close
SITE_SITEID=ID#:
SITE_BUTTON_CHECK=Check
SITE_HINT_SITEID=<font color=red>English character& Numbers Only</font>
SITE_STATUS=Status
SITE_STATUS_NEW=New
SITE_STATUS_FREEZED=Disabled
SITE_STATUS_NORMAL=Enabled
SITE_NAME=Name:
SITE_DOMAIN=Domain:
SITE_FULLTEXT=Building full-text index for this site
SITE_CHARSET=Charset:
SITE_HINT_ENCODING=<b>UTF-8</b> <b>GBK</b> <b>ISO8859-1</b> etc.
SITE_SUFFIX=Suffix:
SITE_HINT_SUFFIX=<b>.jsp</b> <b>.php</b> etc.
SITE_UNIT=Company:
SITE_ROOT=URL of DocumentRoot:
SITE_HINT_ROOT=<font color=red>Empty=<b>/</b></font>
SITE_PUBLISHDIR=DocumentRoot:
SITE_HINT_PUBLISHDIR=such as <b>/web/</b>
SITE_IMGROOT=URL of ImageRoot:
SITE_HINT_IMGROOT=<font color=red>Empty=<b><$URL of DocumentRoot$>/images</b></font>, starting with <b>http</b> for preview
SITE_IMG_PUBLISHDIR=ImageRoot:
SITE_HINT_IMG_PUBLISHDIR=<font color=red>Empty=<b><$DocumentRoot$>/images</b></font>
SITE_ADMIN=Site Admins
SITE_BUTTON_ADD_ADMIN=Add Admin
SITE_BUTTON_DEL_ADMIN=Delete Admin
SITE_HINT_FTP=<b>Ftp hosts for HTMLs</b>
SITE_FTP=Ftp hosts
SITE_BUTTON_ADD_FTP=Add Ftp
SITE_BUTTON_DEL_FTP=Delete Ftp
SITE_FTPNAME=Host Name/IP
SITE_FTPPORT=Port
SITE_FTPROOT=Ftp Root Path
SITE_FTPUSER=User Name
SITE_FTPPASSWORD=User Password
SITE_HINT_IMG_FTP=<b>Ftp hosts for Images</b>
SITE_BUTTON_ADD_IMG_FTP=Add Ftp
SITE_BUTTON_DEL_IMG_FTP=Delete Ftp
SITE_VARS=Global Variables
SITE_VARS_NAME=Variable Name
SITE_VARS_VALUE=Value
SITE_VARS_COMMENT=Comment
SITE_BUTTON_ADD_VAR=Add Var
SITE_BUTTON_DEL_VAR=Delete Var(s)
SITE_HINT_SOLRCORE=<font color=red>Empty=<b>npscore</b></font>
SITE_SOLRFIELDS=SOLR Fields
SITE_BUTTON_ADD_SOLRFIELD=Add Field
SITE_BUTTON_DEL_SOLRFIELD=Delete Field(s)
SITE_SOLRFIELD_NAME=Field Name
SITE_SOLRFIELD_COMMENT=Comment
SITE_KEYWORDLINK_ENABLED=Auto link
SITE_KEYWORDLINK_IGNORECASE=Ignore case
SITE_KEYWORDLINK_CSS=CSS:
SITE_KEYWORDLINK_TARGET=Target:
SITE_KEYWORDLINK_TARGET_HINT=e.g <b>_blank</b>
SITE_KEYWORDLINK_HINT=Input your keyword links here. You can set more than one keyword to a link per line, each keyword seperated by a comma(,), and with the url at last. For example: <b>nps,jwebstar,http://www.jwebstar.com</b> are linking to http://www.jwebstar.com
SITE_WRITE_BUFFERED=Create temp files for buffered output
SITE_THREADS=Publishing Threads:
SITE_THREADS_HINT=System will queue all publishing tasks and will create or stop threads dynamically.