USER_HTMLTITLE=New User
USER_ALERT_NAME_IS_NULL=Please input user name
USER_ALERT_ACCOUNT_IS_NULL=Please input user account
USER_ALERT_PASSWORD_IS_NULL=Please input password
USER_ALERT_PASSWORD_NOT_EQUAL=Please input password again
USER_ALERT_DELETE=All articles and templates created by this user will set to site admin. Are you sure to continue?
USER_BUTTON_SAVE=Save
USER_BUTTON_SAVE_EXCEPT_PASSWORD=Save All Except Password
USER_BUTTON_RESET_PASSWORD=Reset Password
USER_BUTTON_DELETE=Delete
USER_BUTTON_CLOSE=Close
USER_NAME=User Name:
USER_TYPE=Type:
USER_TYPE_NORMAL=Normal
USER_TYPE_SUPER=Super User
USER_UNIT=Department:
USER_ORDER=Index:
USER_ACCOUNT=Account:
USER_PASSWORD=Password:
USER_PASSWORD_AGAIN=Repeat password:
USER_TEL=Phone:
USER_EMAIL=Email:
USER_MOBILE=Mobile:
USER_FAX=Fax:
USER_ROLES=Roles:
USER_ROLES_DOMAIN=Domain
USER_ROLES_NAME=Role Name
USER_ROLES_DESC=Description
USER_ROLES_HINT=Roles List
USER_ROLES_GRANTABLE_HINT=Grantable Roles List