JOB_HTMLTILE=新作业
JOB_ALERT_NAME_IS_NULL=名称不能为空
JOB_ALERT_CODE_IS_NULL=执行代码不能为空
JOB_ALERT_SITE_IS_NULL=没有指定缺省站点
JOB_ALERT_RUNAS_IS_NULL=没有指定运行用户
JOB_ALERT_CRONEXP_IS_NULL=没有时间表达式
JOB_ALERT_DELETE=确认要删除吗？
JOB_ALERT_PAUSE=确认要暂停作业吗？
JOB_ALERT_RESUME=确认要继续作业吗？
JOB_ALERT_ENABLE=确认要启用作业吗？
JOB_ALERT_DISABLE=确认要禁用作业吗？
JOB_ALERT_STOP=确认要终止当前作业吗？
JOB_BUTTON_SAVE=保存
JOB_BUTTON_DELETE=删除
JOB_BUTTON_PAUSE=暂停作业
JOB_BUTTON_RESUME=恢复作业
JOB_BUTTON_STOP=终止正在运行的作业
JOB_BUTTON_DISABLE=禁用
JOB_BUTTON_ENABLE=启用
JOB_BUTTON_RUN_IMMEDIATELY=立即运行
JOB_BUTTON_JS_HELP=JavaScript对象编程手册
JOB_BUTTON_CRONEXP_HELP=查看帮助
JOB_BUTTON_RUNAS=选择
JOB_BUTTON_CLOSE=关闭
JOB_ID=id#
JOB_NAME=名称
JOB_PARAMS=运行参数
JOB_SITE=默认站点
JOB_RUNAS=运行用户
JOB_CRONEXP=时间表达式
JOB_STATUS=状态
JOB_HINT_STATUS_NEW=新建
JOB_HINT_STATUS_BLOCKED=<font color=red>堵塞</font>
JOB_HINT_STATUS_COMPLETE=完成
JOB_HINT_STATUS_ERROR=<font color=red>调度中发生了错误</font>
JOB_HINT_STATUS_NONE=<font color=red>不存在的任务</font>
JOB_HINT_STATUS_NORMAL=正常调度中
JOB_HINT_STATUS_PAUSED=<font color=red>中断中</font>
JOB_HINT_ENABLE=可用
JOB_HINT_DISABLE=<font color=red>禁用</font>
JOB_LANG=语言
JOB_CREATOR=创建人
JOB_CREATEDATE=创建时间
JOB_LASTRUN_SERVER=运行服务器
JOB_LASTRUN_DATE=运行时间
JOB_LASTRUN_TIME=运行时长
JOB_LASTRUN_STATE=运行状态
JOB_LASTRUN_STATUS_NORMAL=正常完成
JOB_LASTRUN_STATUS_ERROR=<font color=red>异常退出</font>
