<div class="top">
  <div class="left">
      <ul>
        <li class="left"><a href="/index.html"><img src="/images/logo.png" /></a></li>
        <li class="left" style="padding-top:20px;"><img src="/images/kuohao.png" /></li>
        </ul>
    </div>
    <div class="right">
      <ul class="text_right"><img src="/images/tel.png" /></ul>
        <ul class="text_center" style="line-height:20px;"><a href="/reglog.shtml">注册</a><a href="/order/cart.do?cmd=view">购物车</a><a href="http://wpa.qq.com/msgrd?V=1&Uin=394188895&Site=http://new.ithinkgo.com&Menu=yes">在线客服</a></ul>
    </div>
</div>