<div class="menu">
  <ul>    <li class="left"><a href="/">首页</a><a href="/cpml/sg">水果</a><a href="/cpml/sc">蔬菜</a><a href="/cpml/ly">粮油</a><a href="/cpml/cy">茶叶</a><a href="/cpml/yp">饮品</a><a href="/cpml/xx">休闲食品</a><a href="/cpml/ttc">土特产</a></li>
    <li class="right">
    <div class="left" style="width:60px;">&nbsp;</div>
    <div class="left"><a href="/">品牌专区</a><a href="/cpml/index_import.shtml">进口食品</a><a href="/cpml/index_nutrition.shtml">健康养生</a><a href="/cpml/twp">我的厨房</a><a href="/">个性定制</a><a href="/">假日采购</a></div>
    </li>
    </ul>
</div>
