<div class="service">
  <ul>
      <li class="tel">
      <a target=blank href=http://wpa.qq.com/msgrd?V=1&Uin=394188895&Site=http://new.ithinkgo.com&Menu=yes><img border="0" SRC="/images/img_17.png" alt="点击这里给我发消息"></a>
      <a target=blank href=http://wpa.qq.com/msgrd?V=1&Uin=1256843456&Site=http://new.ithinkgo.com&Menu=yes><img border="0" SRC="/images/img_17.png" alt="点击这里给我发消息"></a>
      </li>
        <li><span class="font_bold">新手指南</span><br />
        		<a href="/common/help.shtml?cont=cont_newplayer&div=div_newplayer">购物流程</a><br />
        		<a href="/common/help.shtml?cont=cont_newplayer&div=div_newplayer">注册流程</a><br />
        		<a href="/common/help.shtml?cont=cont_newplayer&div=div_newplayer">会员积分</a><br />
        		<a href="/common/help.shtml?cont=cont_newplayer&div=div_newplayer">团购/拼购</a>
        		</li>
        <li><span class="font_bold">付款方式</span><br />
        	<a href="/common/help.shtml?cont=cont_pay&div=div_pay">货到付款</a><br />
        	<a href="/common/help.shtml?cont=cont_pay&div=div_pay">支付宝支付</a><br />
        	<a href="/common/help.shtml?cont=cont_pay&div=div_pay">储值卡使用</a><br />
        	<a href="/common/help.shtml?cont=cont_pay&div=div_pay">发票相关</a></li>
        <li><span class="font_bold">配送方式</span><br />
        <a href="/common/help.shtml?cont=cont_deliver&div=div_deliver">配送费用</a><br />
        <a href="/common/help.shtml?cont=cont_deliver&div=div_deliver">配送时间</a><br />
        <a href="/common/help.shtml?cont=cont_deliver&div=div_deliver">配送范围</a></li>
        <li><span class="font_bold">售后服务</span><br />
        <a href="/common/help.shtml?cont=cont_service&div=div_service">服务保障承诺</a><br />
        <a href="/common/help.shtml?cont=cont_service&div=div_service">价格变更</a><br />
        <a href="/common/help.shtml?cont=cont_service&div=div_service">退/换货政策</a><br />
        <a href="/common/help.shtml?cont=cont_service&div=div_service">退/换货流程</a></li>
        <li class="border"><span class="font_bold">帮助中心</span><br />
        <a href="/common/help.shtml?cont=cont_center&div=div_center">常见问题</a><br />
        <a href="/common/help.shtml?cont=cont_center&div=div_center">联系我们</a><br />
        <a href="/common/help.shtml?cont=cont_center&div=div_center">网站地图</a><br />
        <a href="/common/help.shtml?cont=cont_center&div=div_center">用户使用协议</a></li>
    </ul>
    <div class="firefox"></div>
</div>