<div class="down">
  <ul class="service2">
      <li><img src="/images/service_02.png" /></li>
        <li><img src="/images/service_03.png" /></li>
        <li><img src="/images/service_04.png" /></li>
        <li><img src="/images/service_05.png" /></li>
    </ul>
    <ul><a href="http://www.hznfnet.com">关于我们</a>
    <a href="http://new.ithinkgo.com:8822/common/help.shtml?cont=cont_center&div=div_center">合作伙伴</a>
    <a href="http://new.ithinkgo.com:8822/common/help.shtml?cont=cont_center&div=div_center">广告合作</a>
    <a href="http://new.ithinkgo.com:8822/common/help.shtml?cont=cont_service&div=div_service">客服中心</a>    
    <a href="error.html">供应商合作</a>
    <a href="/common/help.shtml?cont=cont_center&div=div_center#pos_center_lxwm">联系方式</a>
    <a href="/common/help.shtml?cont=cont_pay&div=div_pay">储值卡使用</a>
    <a href="/common/help.shtml">帮助</a></ul>
  <ul>Copyright?2011 www.ithinkgo.com 版权所有 All Right Reerved.</ul>
    <ul>中国·杭州 浙ICP备09076267号</ul>
    <ul><img src="/images/down_01.png" /></ul>
</div>