<div class="link">
  <ul>
      <li class="left"><a target="_blank" href="http://www.cofeed.com/"><img src="/images/img_18.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.cngrain.com/"><img src="/images/img_19.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.aweb.com.cn/"><img src="/images/img_20.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.aptc.cn/"><img src="/images/img_21.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.hznfnet.com/"><img src="/images/img_22.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.cofeed.com/"><img src="/images/img_23.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.agri.gov.cn/"><img src="/images/img_24.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://www.dnce.com.cn"><img src="/images/img_25.png" /></a></li>
        <li class="right"><a target="_blank"  href="http://nc.mofcom.gov.cn"><img src="/images/img_26.png" /></a></li>
    </ul>
    <div class="firefox"></div>
</div>