<div class="about">
  <ul>
      <li class="left"><img src="/images/title_03.png" /></li>
        <li class="right"><img src="/images/title_04.png" /></li>
    </ul>
    <ul>
    想购网-专业致力于农副产品及食品网上销售。依托杭州农副产品物流中心，我们倾力打造国内优秀的农副产品及食品垂直领域电子商务平台。我们拥有完善的仓储、物流配送体系，根据客户的需求将绿色新鲜食品直接配送上门。我们通过渠道与供应商整合在线销售绿色食品、健康食品、新鲜水果、进口食品、国产食品等品种，随着业务的不断深入，我们将整合全国乃至全球优秀的产品供应商、产地，让您足不出户享受一站式网上购物体验！
    </ul>
    <ul>请记住我们的网址：<a href="http://www.ithinkgo.com" class="text_red">http://www.ithinkgo.com</a></ul>
    <div class="firefox"></div>
</div>