<div class="search">
<div class="left"><form action="/solrresult.shtml" ><input id="key" name="key" type="text" value="想找什么？" class="input" /><input name="" type="submit" value="搜索" /></form></div>
<div class="left">他们在找：
    <a href="/solrresult.shtml?key=橙">橙</a>
    <a href="/solrresult.shtml?key=黄瓜">黄瓜</a>
    <a href="/solrresult.shtml?key=杨桃">杨桃</a>
    <a href="/solrresult.shtml?key=杨桃">杨桃</a>
    <a href="/solrresult.shtml?key=梨">梨</a>
    <a href="/solrresult.shtml?key=青提">青提</a>
    <a href="/solrresult.shtml?key=蓝莓">蓝莓</a>
    <a href="/solrresult.shtml?key=櫻桃">櫻桃</a>
    <a href="/solrresult.shtml?key=柠檬">柠檬</a>
    <a href="/solrresult.shtml?key=柚子">柚子</a>
    <a href="/solrresult.shtml?key=龙眼">龙眼</a>
    <a href="/solrresult.shtml?key=荔枝">荔枝</a>
    <a href="/solrresult.shtml?key=椰子">椰子</a>
    <a href="/solrresult.shtml?key=芒果">芒果</a>
    <a href="/solrresult.shtml?key=榴莲">榴莲</a>
    <a href="/solrresult.shtml?key=山竹">山竹</a>
    <a href="/solrresult.shtml?key=木瓜">木瓜</a>
    <a href="/solrresult.shtml?key=猕猴桃">猕猴桃</a>
  </div>
</div>